#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /home/eadlam/projects/MPC/mwc.pl -type make -features vrep=0,tests=0,docs=1 workspace.mwc
#
#----------------------------------------------------------------------------


all: madara_sudoku documentation_madara_sudoku

depend: madara_sudoku-depend documentation_madara_sudoku-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.madara_sudoku $(@)
	@cd docs && $(MAKE) -f Makefile.documentation_madara_sudoku $(@)

.PHONY: madara_sudoku
madara_sudoku:
	@$(MAKE) -f Makefile.madara_sudoku all

.PHONY: madara_sudoku-depend
madara_sudoku-depend:
	@$(MAKE) -f Makefile.madara_sudoku depend

.PHONY: documentation_madara_sudoku
documentation_madara_sudoku:
	@cd docs && $(MAKE) -f Makefile.documentation_madara_sudoku all

.PHONY: documentation_madara_sudoku-depend
documentation_madara_sudoku-depend:
	@cd docs && $(MAKE) -f Makefile.documentation_madara_sudoku depend

project_name_list:
	@echo madara_sudoku
	@echo documentation_madara_sudoku
